create table if not exists public.work_logs (
  id bigint generated by default as identity primary key,
  data date not null,
  dzien_tygodnia text,
  linia text not null,
  zmiana integer not null,
  godziny_plan numeric not null default 8,
  godziny_fakt numeric not null default 8,
  nadgodziny numeric not null default 0,
  godziny_nocne numeric not null default 0,
  komponenty_ok integer not null default 0,
  komponenty_nok integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists work_logs_unique_shift
  on public.work_logs (data, linia, zmiana);

create index if not exists work_logs_data_desc_idx
  on public.work_logs (data desc);
